[package]
name = 'TokenMint'
version = '1.0.0'
authors=["Rahul Srivastava (rahul@chingari.io)"]

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'


[dependencies.AptosTokenObjects]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-token-objects'


[addresses]
admin='_'
GiftNfts='_'